### PR TITLE
fix(actions): add fetch-depth and git fetch

### LINKED ISSUE #777: pathspec 'develop' did not match any file(s) known to git
**Describe the bug**

I use `shipjs trigger` with github actions.
But actions can't checkout baseBranch `develop`.
Error log is [here](https://github.com/gridsome/eslint-plugin-gridsome/runs/617765300?check_suite_focus=true).

base branch => develop
release branch => master

**To Reproduce**
1. Run `npm run release:prepare` on develop.
2. merge PR.
3. There is error...

**Expected behavior**
Pass shipjs trigger

**Screenshots**

**Environment (please complete the following information):**
 - environment: (your local machine, CircleCI, Travis CI, etc.)
 - `node -v`: 12.x
 - `npm -v` or `yarn -v`: 
- Ship.js version: 0.18.2

**Additional context**
It might be caused by actions/checkout@v2😭

### PR DESCRIPTION
**Pull request by tyankatsu0105**
# What
fix #777 

Add `fetch-depth: 0` and `git fetch` to github getBaseConfig.

### CODE REVIEW

**Comment by tyankatsu0105** [comment]
@jeetiss 
How about this PR?

**Comment by eunjae-lee** [comment]
Thank you both @tyankatsu0105 and @jeetiss !
I have a question. We didn't have this option before but why was it working before and not any more?
Has GitHub Actions changed?
Or @tyankatsu0105 's repo or setting is related?

**Comment by tyankatsu0105** [comment]
@eunjae-lee 
Exactly. I don't know about GitHub Actions very much.
I think we need a repository to reproduce this problem.🤔

**Comment by tyankatsu0105** [comment]
@eunjae-lee 
There is an same error at this actions.
https://github.com/tyankatsu0105/eslint-with-typescript/runs/628194075?check_suite_focus=true

@jeetiss 
I think you know about GitHub Actions very much.
Do you know why there is an error?

**Comment by eunjae-lee** [comment]
@tyankatsu0105 I guess the change in this PR makes sense.
Does the change also fix the issue in eslint-with-typescript package?

**Comment by tyankatsu0105** [comment]
@eunjae-lee 
Yes.
Now I add `git fetch` and `fetch-depth: 0`. 
It looks like working correctly.
https://github.com/tyankatsu0105/eslint-plugin/runs/629421080?check_suite_focus=true

**Comment by jeetiss** [comment]
Hello @eunjae-lee and @tyankatsu0105 

> We didn't have this option before but why was it working before and not any more?
Has GitHub Actions changed?

No, GHA has not changed, it didn't work because I did not test this staff)

But, now everything is okey. Kudos to @tyankatsu0105

**Comment by eunjae-lee** [comment]
Oh, then this must be not tested with `toReleaseBranch` strategy.
Thanks @tyankatsu0105 and @jeetiss 😁

**Pull request merged**
