### PR TITLE
fix: fix hubConfigured for GitHub Actions

### LINKED ISSUE #316: Running shipjs on GitHub Actions
**Describe the bug**
Failed to push tag to the repo while `shipjs trigger`.

https://github.com/uetchy/create-whatever/commit/2670594b2cb0b5635c00067da67d2e6bb262735e/checks?check_suite_id=257704743#step:7:36

**To Reproduce**
Run shipjs on GitHub Actions with [this workflow config](https://github.com/uetchy/create-whatever/blob/master/.github/workflows/main.yml).

```yaml
jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - uses: geertvdc/setup-hub@master
      - run: git switch master
      - run: yarn install
      - run: yarn release:trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
```

**Environment (please complete the following information):**
- Ship.js version: 0.6.0

**Additional context**
- `NPM_AUTH_TOKEN` and `GITHUB_TOKEN` has been set.

### PR DESCRIPTION
**Pull request by eunjae-lee**
closes #316

### CODE REVIEW

**Comment by eunjae-lee** [comment]
@uetchy Hi there, 
Since I don't have access to GitHub actions, I cannot test this by myself :(
For now, the easiest way to fix this issue seems to be using `hub release` instead of `hub api user`.
What do you think?
Will this work? Could you test this for me if you don't mind?

**Comment by uetchy** [comment]
`hub release` would work for verifying token but not verify it is privileged to create a release on a repository.
Checking the result of `hub api repos/<user>/<repo> | jq .permissions.push` might work; If it returns `true`, it means with provided GITHUB_TOKEN you can create a release on the repo.
Anyway I'll test this PR on my own project to see what happens.

**Comment by uetchy** [comment]
Is it possible to publish this PR as an npm module?

**Comment by uetchy** [comment]
btw `npm i algolia/shipjs#fix/gh-action` end up failing with error: `/bin/sh: 1: rollup: not found`
https://github.com/vibranthq/opinionated-review/commit/50982441dfa47e49206680e5a0821dafb71cee97/checks?check_suite_id=297781477#step:6:10

**Comment by uetchy** [comment]
Finally, it worked out
https://github.com/vibranthq/opinionated-review/commit/f665188ec6b35eb3b9627a0096e4243ae863b13f/checks?check_suite_id=297843606

**Comment by uetchy** [comment]
Screen Shot 2019-11-06 at 16 15 22
🚀

**Comment by eunjae-lee** [comment]
> `hub release` would work for verifying token but not verify it is privileged to create a release on a repository.
> Checking the result of `hub api repos/<user>/<repo> | jq .permissions.push` might work; If it returns `true`, it means with provided GITHUB_TOKEN you can create a release on the repo. Perhaps it is easier to use octokit module than `hub` to do such a task.

Thanks for the test 🚀 
And thanks again for the explanation.
At the moment, verifying token sounds enough and we can add code later to check if the token is privileged to create release when needed.

**Pull request merged**
