### PR TITLE
feat: upload assets to GitHub release

### LINKED ISSUE #332: Upload assets to GitHub release
**Is your feature request related to a problem? Please describe.**
As we can create a GitHub release now, it's at a good point to take the next step and let ship.js upload assets to a release at GitHub.

**Describe the solution you'd like**

#### 1. Define config something like this

```js
module.exports = {
  releases: {
    assetsToUpload: ["build/App.zip"]
  }
};
```

#### 3. Upload assets while creating a release

```
hub release create -a "<filepath>#<label>" <tag>
```

I'm ready for working this on.

### PR DESCRIPTION
**Pull request by uetchy**
Adding support for uploading assets to GitHub release.

Fixes #332

### CODE REVIEW

**Comment by eunjae-lee** [comment]
Now that I see your code, I feel like we need to change `assetsToUpload` to a function returning an array.
The assets to upload can be different from versions. For example, if your bundle is like `my-lib-1.2.3.zip`, then `assetsToUpload` needs to dynamically return the file name.

```
releases: {
  assetsToUpload: ({ version, dir }) => []
}
```

What do you think? Do you find any other parameters useful there besides version and dir?

**Comment by uetchy** [comment]
Seems nice! I'm figuring `tagName` is also useful.

Another possible option is accepting glob pattern.

```js
releases: {
  assetsToUpload: "dist/*.zip"
}
```

Those options can be considered.
1. singular file, list, function
2. singular file (glob), list (glob)
3. singular file (glob), list (glob), function

**Comment by eunjae-lee** [comment]
> 1. singular file, list, function
> 2. singular file (glob), list (glob)
> 3. singular file (glob), list (glob), function

3 sounds complete, but you could do 1 first and 3 later if it's too big for you to work on at the moment.

**Comment by uetchy** [comment]
added

**Comment by uetchy** [comment]
`assetsToUpload` accepts both Function and Promises.

**Comment by eunjae-lee** [comment]
@uetchy
Nice work! It looks good to me.
Can you test one thing?
I'm worried if it won't work when any of path contains a space.
For example, there's a file named `/path/hello world.zip`, and the command will become
`hub release create -a /path/hello world.zip -a /another/file.zip`
That space needs to be escaped, but not sure how to properly do it, covering cross platforms.

**Comment by uetchy** [comment]
@eunjae-lee OK now I added `shell-quote` to quote asset path containing spaces.
And also wrote a test for them.

**Comment by eunjae-lee** [comment]
Congrats and thanks for your contribution. I really appreciate it 🙂

**Comment by uetchy** [comment]
Awesome😎

**Pull request merged**
