### PR TITLE
chore(github actions): use `actions/github-script` in place of deprec…

### PR DESCRIPTION
**Pull request by fmal**
…ated `actions/github`

### CODE REVIEW

**Comment by eunjae-lee** [comment]
Hi @fmal, Thanks for opening the PR 🙂 
Could you give us more context on this PR?

And @jeetiss, could you review this?

**Comment by eunjae-lee** [comment]
Closing this due to the lack of activity. I'm not well aware of GitHub Actions. So if you provide any materials, then I'll learn and review this (or delegate it).

**Comment by fmal** [comment]
Hi @eunjae-lee, sorry for inactivity. I'm not sure if there's much to add here. Basically https://github.com/actions/github which is currently in the codebase has been deprecated (see readme note) and archived in favour of https://github.com/actions/github-script. All i've done here is a simple migration from `actions/github` to `actions/github-script` as the docs recommend. Some syntax changed but functionally it's the same.

**Comment by eunjae-lee** [comment]
Hey @fmal, Thanks for the context :)
I will review this and merge it soon.

**Comment by fmal** [comment]
@eunjae-lee any reason why you decided not to merge? 😃

**Comment by eunjae-lee** [comment]
Hey @fmal, I guess this was closed because I changed the base branch to `main` from `master`. I'm in a meeting right now, so I will come back here soon.

**Comment by eunjae-lee** [comment]
This looks good to me.
Can @tyankatsu0105 take a look as well?

**Comment by tyankatsu0105** [comment]
It looks good.

I don't know about `github-script`.
But GitHub Actions team recommends use `github-script` instead of `github`.
>🚨 This action is deprecated! Please use actions/github-script, instead.

**Pull request merged**
