### PR TITLE
fix(setup): add eslint disable comment to ship.config.js

### PR DESCRIPTION
**Pull request by eunjae-lee**

### CODE REVIEW

**Comment by francoischalifour** [comment]
This might be too tied to the InstantSearch ESLint configuration?

**Comment by eunjae-lee** [comment]
@francoischalifour It might be. I thought if user uses ESLint in their project, they'll probably need this comment.
Too much?

**Comment by francoischalifour** [comment]
Not necessarily. Some codebases use CJS imports: Node modules and some front-end libraries.

**Comment by eunjae-lee** [comment]
It makes sense!

**Pull request merged**
