### PR TITLE
chore: release v0.11.0

### PR DESCRIPTION
**Pull request by eunjae-lee**
## Release Summary
- Version change: `v0.10.0` → `v0.11.0`
- Merge: `releases/v0.11.0` → `master`
- [Compare the changes between the versions](https://github.com/algolia/shipjs/compare/v0.10.0...releases/v0.11.0)
> :warning: When merging this pull request, you need to **_"Squash and merge"_** and make sure the title starts with `chore: release v0.11.0`.
> After that, a commit `chore: release v0.11.0` will be added and `shipjs trigger` will be able to trigger the release based on the commit.
> Fore more information, please refer to the mergeStrategy section of the [guide](https://github.com/algolia/shipjs/blob/master/GUIDE.md#mergestrategy).
> Squash and merge

---
_This pull request is automatically generated by [Ship.js](https://github.com/algolia/shipjs)_

### CODE REVIEW

**Comment by eunjae-lee** [comment]
`0.11.0` includes the removal of `hub`, which is huge!

With `hub`, when user ran `shipjs prepare` command, `hub` worked fine with GitHub token inside the hub configuration.
Now that we don't use `hub`, we need to have GitHub token inside Ship.js to create pull request at `shipjs prepare`.
So unavoidably, `GITHUB_TOKEN` is required as an environment variable. It is documented in the guide.

Besides, this release is relatively bigger/riskier than previous ones.

Is there anyone who could help testing this branch before we release it?
Please let me know if you think it works fine or have any feedback on this.

You can check out this branch and run command like the following:

```
yarn workspace shipjs test:run:prepare --dir <your project path>
```

Pinging all the code contributors @uetchy @jeetiss @jamesgeorge007 @kazupon

I've ran all the flows by myself, so I'm pretty sure it's okay, but I'd like to get some confirmation from you all :)

**Comment by jeetiss** [comment]
Nice, everything works 🙌🏻
https://github.com/jeetiss/try-shipjs/pull/5

**Comment by uetchy** [comment]
@jeetiss Looks like `createGitHubRelease` stopped working?
https://github.com/jeetiss/try-shipjs/releases

**Comment by jeetiss** [comment]
@uetchy yes, I had this problems too, when ran `shipjs` first time on empty repo 

> Looks like createGitHubRelease stopped working?

Yep, looks like it wasn't working, but now everything is ok
https://github.com/jeetiss/try-shipjs/releases

**Comment by eunjae-lee** [comment]
@uetchy cc @jeetiss 
okay, so it's about not having `build` or `test` command in projects, not not about this release, right?
Then I will ship this version first, and then later will come up with the issue in the next version.
Thanks for addressing the issue 👍

**Pull request merged**
